fun main() {
//    val manager = ResourceManager()
//    val gas = OutpostResource(1,"Gas", 100)
//    val mineral = OutpostResource(2,"Mineral", 200)
//    manager.add(gas)
//    manager.add(mineral)
//    manager.printAll()
//    val bonusMineral = mineral.copy(id = 3, amount = mineral.amount + 100)
//    println("Бонусные минералы: $bonusMineral")
    val manager = ResourceManager()
    manager.add(OutpostResource(1, "Minerals", 120))
    manager.add(OutpostResource(2, "Gas", 40))
    val generator = EnergyGenerator()
    val lab = ResearchLab()
    generator.performAction(manager)
    lab.performAction(manager)
    println()
    manager.printAll()
}